name: Checks

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.43.0
          cache: true
          environments: dev

      - name: Run pre-commit
        run: pixi run -e dev pre-commit
